
name: V2Ray Config Collector
on:
  push:
    branches:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install httpx[http2] beautifulsoup4 pydantic jdatetime aiofiles geoip2
      - name: Run V2Ray Collector
        run: python main.py
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          if ! git diff --staged --quiet; then
            git commit -m "📊 Update V2Ray configs - $(date)"
            git push
          else
            echo "No changes to commit."
          fi
